# Generated by Django 5.0.1 on 2024-04-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_profile_options_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('inlove', 'In Love')], default='single', max_length=100),
        ),
    ]
