# Generated by Django 5.0.1 on 2024-03-30 07:57

import django.db.models.deletion
import shortuuid.django_fields
import userauths.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='Everyone', max_length=100),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='Everyone', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='Everyone', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='Everyone', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='Everyone', max_length=100),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000000)),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', length=7, max_length=25, prefix='')),
                ('chat_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_receiver', to=settings.AUTH_USER_MODEL)),
                ('chat_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Messages',
            },
        ),
    ]
