# Generated by Django 5.0.1 on 2024-04-11 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Personal Chat'},
        ),
    ]
