# Generated by Django 5.0.1 on 2024-05-15 03:54

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_groupchat_groupchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='group-cover.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
