# Generated by Django 5.0.1 on 2024-05-29 08:48

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
