# Generated by Django 5.0.1 on 2024-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_chatmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=100000000),
        ),
    ]
