# Generated by Django 5.0.1 on 2024-05-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_chatmessage_image_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
