# Generated by Django 5.0.1 on 2024-06-03 04:18

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_groupchat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='images',
            field=models.FileField(blank=True, default='profile-cover.jpg', null=True, upload_to='group_chat'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
